### ISSUE TITLE
illegal memory access

### ISSUE THREAD

**Issue by Guoxs** [NVIDIA-AI-IOT/CUDA-PointPillars#7]
Cuda failure: an illegal memory access was encountered at line 306 in file .../CUDA-PointPillars/src/pointpillar.cpp error status: 700

**Comment by Guoxs** [comment]
X86 platform

**Comment by darrenearl** [comment]
@Guoxs

**Comment by Miki-lin** [comment]
I  meet this problem too, can you tell me how to fix it?

**Comment by Miki-lin** [comment]
> hi, how do you solve this problem?

hi, how do you fix this problem?

**Comment by Guoxs** [comment]
I cannot reproduce this bug in later commits , so I closed this issue...

**Comment by Miki-lin** [comment]
> I cannot reproduce this bug in later commits , so I closed this issue...

I reproduce this bug in different file, so I'm wondering what is causing this problem.

**Comment by JiyuanWANG12138** [comment]
> I fix this problem by cleaning the build folder, please make sure that params and onnx are consistent, and rebuild it!

Hello,did you still have this problem? I cleaned the build folder and rebuilt it again, but it still have this problems, I used ros to get the cloudpoints, in most frames it works well, but in some frame, it died with this problem "Cuda failure: an illegal memory access was encountered at line 306 in file .../CUDA-PointPillars/src/pointpillar.cpp error status: 700", I don't understand... I will be very apperciate if you can help me.

**Comment by JiyuanWANG12138** [comment]
> hi, how do you solve this problem?

Hello , did you solve this problem now?

**Comment by yumendecc** [comment]
Cuda failure: an illegal memory access was encountered at line 239 in file CUDA-PointPillars/src/pointpillars/pointpillar.cpp error status: 700
我的代码也报了类似错误，可以增加MAX_VOXELS的大小解决了，如果输入点云产生的pillar数量大于MAX_VOXELS时会产生访问越界，在核函数没有进行限制导致出错

**Comment by JiyuanWANG12138** [comment]
> Cuda failure: an illegal memory access was encountered at line 239 in file CUDA-PointPillars/src/pointpillars/pointpillar.cpp error status: 700 我的代码也报了类似错误，可以增加MAX_VOXELS的大小解决了，如果输入点云产生的pillar数量大于MAX_VOXELS时会产生访问越界，在核函数没有进行限制导致出错

谢谢您的解答，我使用了更大的MAX_VOXELS,可是他还是报错了，请问您是在执行到哪一步的时候报错了呀，我的是在执行完PostProcessCuda()后，执行checkCudaErrors(cudaDeviceSynchronize())这一步，针对某些帧出现该错误，导致程序中断，对于大多数帧来说都是可以正常运行的。

**Comment by yumendecc** [comment]
> > Cuda failure: an illegal memory access was encountered at line 239 in file CUDA-PointPillars/src/pointpillars/pointpillar.cpp error status: 700 我的代码也报了类似错误，可以增加MAX_VOXELS的大小解决了，如果输入点云产生的pillar数量大于MAX_VOXELS时会产生访问越界，在核函数没有进行限制导致出错
> 
> 谢谢您的解答，我使用了更大的MAX_VOXELS,可是他还是报错了，请问您是在执行到哪一步的时候报错了呀，我的是在执行完PostProcessCuda()后，执行checkCudaErrors(cudaDeviceSynchronize())这一步，针对某些帧出现该错误，导致程序中断，对于大多数帧来说都是可以正常运行的。

在调用pre_->generateVoxels后的 checkCudaErrors(cudaDeviceSynchronize());报错

**Comment by JiyuanWANG12138** [comment]
> > > Cuda failure: an illegal memory access was encountered at line 239 in file CUDA-PointPillars/src/pointpillars/pointpillar.cpp error status: 700 我的代码也报了类似错误，可以增加MAX_VOXELS的大小解决了，如果输入点云产生的pillar数量大于MAX_VOXELS时会产生访问越界，在核函数没有进行限制导致出错
> > 
> > 
> > 谢谢您的解答，我使用了更大的MAX_VOXELS,可是他还是报错了，请问您是在执行到哪一步的时候报错了呀，我的是在执行完PostProcessCuda()后，执行checkCudaErrors(cudaDeviceSynchronize())这一步，针对某些帧出现该错误，导致程序中断，对于大多数帧来说都是可以正常运行的。
> 
> 在调用pre_->generateVoxels后的 checkCudaErrors(cudaDeviceSynchronize());报错

哎，那我们的报错地方不一样哎，我是后处理完了同步时报的错，你有什么想法吗？感恩！

**Comment by yumendecc** [comment]
研究一下他的核函数吧😂



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 8, 2023 16:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [NVIDIA-AI-IOT/CUDA-PointPillars] illegal memory access (Issue#7)




    
Cuda failure: an illegal memory access was encountered at line 239 in file CUDA-PointPillars/src/pointpillars/pointpillar.cpp error status: 700 我的代码也报了类似错误，可以增加MAX_VOXELS的大小解决了，如果输入点云产生的pillar数量大于MAX_VOXELS时会产生访问越界，在核函数没有进行限制导致出错
  
谢谢您的解答，我使用了更大的MAX_VOXELS,可是他还是报错了，请问您是在执行到哪一步的时候报错了呀，我的是在执行完PostProcessCuda()后，执行checkCudaErrors(cudaDeviceSynchronize())这一步，针对某些帧出现该错误，导致程序中断，对于大多数帧来说都是可以正常运行的。
  
在调用pre_-&gt;generateVoxels后的 checkCudaErrors(cudaDeviceSynchronize());报错
  
哎，那我们的报错地方不一样哎，我是后处理完了同步时报的错，你有什么想法吗？感恩！

**Comment by JiyuanWANG12138** [comment]
> > > Cuda failure: an illegal memory access was encountered at line 239 in file CUDA-PointPillars/src/pointpillars/pointpillar.cpp error status: 700 我的代码也报了类似错误，可以增加MAX_VOXELS的大小解决了，如果输入点云产生的pillar数量大于MAX_VOXELS时会产生访问越界，在核函数没有进行限制导致出错
> > 
> > 
> > 谢谢您的解答，我使用了更大的MAX_VOXELS,可是他还是报错了，请问您是在执行到哪一步的时候报错了呀，我的是在执行完PostProcessCuda()后，执行checkCudaErrors(cudaDeviceSynchronize())这一步，针对某些帧出现该错误，导致程序中断，对于大多数帧来说都是可以正常运行的。
> 
> 在调用pre_->generateVoxels后的 checkCudaErrors(cudaDeviceSynchronize());报错

哎，那我们的报错地方不一样哎，我是后处理完了同步时报的错，你有什么想法吗？感恩！

**Comment by JiyuanWANG12138** [comment]
不知道从哪下手研究哎，之前没有接触过c++的cuda。应该看后处理那部分吗

yumendecc ***@***.***> 于2023年2月8日周三 16:16写道：

**Comment by zzt007** [comment]
> > I fix this problem by cleaning the build folder, please make sure that params and onnx are consistent, and rebuild it!
> 
> Hello,did you still have this problem? I cleaned the build folder and rebuilt it again, but it still have this problems, I used ros to get the cloudpoints, in most frames it works well, but in some frame, it died with this problem "Cuda failure: an illegal memory access was encountered at line 306 in file .../CUDA-PointPillars/src/pointpillar.cpp error status: 700", I don't understand... I will be very apperciate if you can help me.
>
>
>您好，我也是用这个项目改ROS，在generaterVoxels之后也报了这个错误，想咨询一下您如何解决这个问题的呢？非常感激！
